export const ADD_CONTACT = 'ADD_CONTACt';
export const SET_EDIT_CONTACT = 'SET_EDIT_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
